
<?php

const DB_NAME = "Wow";
const DB_HOST = "localhost";
const DB_USER = "root";
const DB_PASSWORD = "Password";

const MAX_HEALTH_HUMAN = 100;
const MAX_HEALTH_DUNGEON_MASTER = 999;
const MAX_HEALTH_DARK_IRON_DWARF = 120;
const MAX_HEALTH_ELF = 90;
const MAX_HEALTH_FORSAKEN = 110;
const MAX_HEALTH_ORK = 180;

const MAX_MANA_HUMAN = 100;
const MAX_MANA_DUNGEON_MASTER = 999;
const MAX_MANA_DARK_IRON_DWARF = 100;
const MAX_MANA_ELF = 100;
const MAX_MANA_FORSAKEN = 100;
const MAX_MANA_ORK = 100;

const COURAGE_HUMAN = 10;
const COURAGE_DUNGEON_MASTER = 99;
const COURAGE_DARK_IRON_DWARF = 12;
const COURAGE_ELF = 9;
const COURAGE_FORSAKEN = 11;
const COURAGE_ORK = 18;

const STRENGTH_HUMAN = 10;
const STRENGTH_DUNGEON_MASTER = 99;
const STRENGTH_DARK_IRON_DWARF = 12;
const STRENGTH_ELF = 9;
const STRENGTH_FORSAKEN = 11;
const STRENGTH_ORK = 18;

const INTELLIGENCE_HUMAN = 10;
const INTELLIGENCE_DUNGEON_MASTER = 99;
const INTELLIGENCE_DARK_IRON_DWARF = 12;
const INTELLIGENCE_ELF = 9;
const INTELLIGENCE_FORSAKEN = 11;
const INTELLIGENCE_ORK = 18;

const WEAPON_HUMAN = "Sword";
const WEAPON_DUNGEON_MASTER = "True Power Spell";
const WEAPON_DARK_IRON_DWARF = "Axe";
const WEAPON_ELF = "Bow";
const WEAPON_FORSAKEN = "Bone";
const WEAPON_ORK = "Mace";

const WEAPON_POWER_SWORD = 100;
const WEAPON_POWER_BONE = 10;
const WEAPON_POWER_AXE = 130;
const WEAPON_POWER_BOW = 7;
const WEAPON_POWER_MACE = 80;
const WEAPON_POWER_TRUE_POWER_SPELL = 999;