
<?php

const MAX_HEALTH_HUMAN = 100;
const MAX_HEALTH_DUNGEON_MASTER = 999;
const MAX_HEALTH_DARK_IRON_DWARF = 120;
const MAX_HEALTH_ELF = 90;
const MAX_HEALTH_FORSAKEN = 110;
const MAX_HEALTH_ORK = 180;